drop table if exists product_orders;
create table product_orders (
	id integer generated by default as identity(start with 1) primary key,
	prod_id integer,
	first_name varchar(255),
	last_name varchar(255)
);

insert into product_orders (prod_id, first_name, last_name) values ('1, 'ravi', 'sil');
insert into product_orders (prod_id, first_name, last_name) values (2, 'Janee', 'do');
insert into product_orders (prod_id, first_name, last_name) values ('3, 'John', 'Doe');

select * from product_orders;
